runtime: custom 
env: flex

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  WEATHER_API_KEY: ${WEATHER_API_KEY}  # Placeholder for the API key, to be replaced during deployment