# version: "3.8"

services:
  weather_api:
    env_file:
      - .env # Load environment variables from .env file
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WEATHER_API_KEY=${WEATHER_API_KEY}
    image: weather_api:1.0
    container_name: weather_api_container
    ports:
      - "8080:8080"
    